# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20171026_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
